### ISSUE TITLE
Publish a new version sql-limiter to npm

### ISSUE THREAD

**Issue by mariadb-ThienLy** [sqlpad/sql-limiter#40]
Hi, Do you have any plan to publish a new version of this library to npm?
https://www.npmjs.com/package/sql-limiter

**Comment by rickbergfalk** [comment]
Oh yes let me do that - sorry I lost track of this @mariadb-ThienLy 

Have a newborn at home :blush:

**Comment by rickbergfalk** [comment]
3.1.0 is available on npm!

**Comment by mariadb-ThienLy** [comment]
Congrats on the new baby!
No need to apologize. You've built a great library that’s helping the community.
